### ISSUE TITLE
有没有哪位大佬教教小弟如何将mw1.bin脱壳还原代码

### ISSUE THREAD

**Issue by mz21g** [davinci1010/pinduoduo_backdoor#10]
我用die，exeinfo和pied都没能查出来它是vmp壳，作者会不后是因为这个文件是放在vmp_src文件夹里，才发现的这个加了vmp壳呢，另外bin文件脱壳方法能否教教小弟

**Comment by mochaaP** [comment]
此 vmp 非彼 vmp（VMProtect Software 出品的商業產品）。這種「vmp」指的是自行實現了smali轉成自行實現的opcode/轉製成c再加殼。

處理思路有很多資料了，此處不概述。

**Comment by mz21g** [comment]
多谢多谢，这就够了

**Comment by goodbranch** [comment]
> 多谢多谢，这就够了

怎么弄的呀
