### ISSUE TITLE
散了吧，315估计不会有他

### ISSUE THREAD

**Issue by cc-ifish** [davinci1010/pinduoduo_backdoor#14]
赌一瓶可乐盲猜拼多多屁事没有。

**Comment by r1172464137** [comment]
![你说法治我都觉得有点好笑](https://user-images.githubusercontent.com/29038520/223770427-033a18c4-d5dd-4850-b7d7-9b83a83f3817.jpg)

**Comment by ananwanan** [comment]
> ![你说法治我都觉得有点好笑](https://user-images.githubusercontent.com/29038520/223770427-033a18c4-d5dd-4850-b7d7-9b83a83f3817.jpg)

我就猜到会有这张图🤣

**Comment by chinnsenn** [comment]
315自己都招商赞助，有啥可信度

**Comment by ananwanan** [comment]
> 315自己都招商赞助，有啥可信度

那确实哈哈哈哈哈哈哈哈哈，蛇鼠一窝。

**Comment by SuperMan9328** [comment]
315有拼多多啊，你看看赞助商

**Comment by hamflx** [comment]
@SuperMan9328 老哥给个传送门，刚刚粗略看了一眼 315，没找到。主要 315 视频太长了，给点提示是开头、结尾还是中间，我再仔细去找找。

**Comment by ananwanan** [comment]
> @SuperMan9328 老哥给个传送门，刚刚粗略看了一眼 315，没找到。主要 315 视频太长了，给点提示是开头、结尾还是中间，我再仔细去找找。

他的意思是，315赞助商里面有拼多多，吃人嘴软，拿人手短。

**Comment by Pmaru-top** [comment]
如果要管，每一天都可以是315，別入戲太深了
