### ISSUE TITLE
举报途径

### ISSUE THREAD

**Issue by Sed66666** [davinci1010/pinduoduo_backdoor#29]
公安部 网络犯罪举报 http://cyberpolice.mps.gov.cn/wfjb/frame/impeach/chooseImpeachAnonymous.jsp
中央网信办（国家互联网信息办公室）举报中心 https://www.12377.cn/index.html

虽然举报了不一定有结果，但是不举报肯定没有结果

**Comment by hsyodyssey** [comment]
我有个更好的建议，去美国SEC举报，PDD是美股上市公司

**Comment by orca-zhang** [comment]
保活看护举报到 网信办
个人信息窃取举报到 工信部网安局数据安全处 或者 上海通管局

**Comment by WHaveFun** [comment]
> 

老哥搞个教程，方便快速裂变啊～

**Comment by WHaveFun** [comment]
> 我有个更好的建议，去美国SEC举报，PDD是美股上市公司

老哥搞个教程，方便快速裂变啊～

**Comment by runningabcd** [comment]
起始最该查的就是上海 gov，他们一直在保护拼多多

**Comment by henryxie2093** [comment]
如果您想向美国证券交易委员会（SEC）举报一家在美国上市的公司窃取用户隐私，可以按照以下步骤进行：

1.收集证据：在向SEC提交举报之前，需要收集足够的证据证明该公司存在窃取用户隐私的行为。例如，可以保存该公司的隐私政策、用户数据协议、相关证据和文档等。

2.填写表格：您需要填写SEC提供的表格，称为“投资者投诉表格（Investor Complaint Form）”，该表格可以在SEC网站上找到。

3.提交表格：您可以通过邮寄、传真或电子邮件的方式提交填写好的表格，SEC官网上提供了详细的提交方式。如果您有进一步的证据或信息可以在表格中附加说明。

4.等待回复：SEC会评估您的投诉并进行调查。您可能会被要求提供进一步的证据或信息。SEC可能会联系您进一步了解您的投诉，或者告知您有关调查结果的信息。

需要注意的是，SEC主要关注的是公司是否违反了证券法规和规定，而不是公司的隐私政策是否存在问题。因此，如果您的投诉只涉及公司的隐私政策问题，您可能需要考虑联系其他机构或机构进行投诉。

来自chatgpt

**Comment by yhm2046** [comment]
在目前TC的大环境下用Android原生系统会不会相对安全? 还是说只能用苹果或者功能手机?

**Comment by PetPotPat** [comment]
> 在目前TC的大环境下用Android原生系统会不会相对安全? 还是说只能用苹果或者功能手机?

原生？原生不就是一毛坯房？比定制系统更破吧

**Comment by imamiao** [comment]
> > 在目前TC的大环境下用Android原生系统会不会相对安全? 还是说只能用苹果或者功能手机?
> 
> 原生？原生不就是一毛坯房？比定制系统更破吧

还真不是，原生系统最起码安全更新是很及时的

**Comment by wuyilingwei** [comment]
> 公安部 网络犯罪举报 http://cyberpolice.mps.gov.cn/wfjb/frame/impeach/chooseImpeachAnonymous.jsp 中央网信办（国家互联网信息办公室）举报中心 https://www.12377.cn/index.html
> 
> 虽然举报了不一定有结果，但是不举报肯定没有结果

多半没用，上面罩着呢
