### ISSUE TITLE
拼多多出动，批量举报

### ISSUE THREAD

**Issue by Asura88** [davinci1010/pinduoduo_backdoor#47]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/25000885/224233765-5195f16a-f41c-482f-a664-1cf72796651e.png">

**Comment by zhangjg0201** [comment]
代码都被人爆出来了， 还有脸说这话

**Comment by paradiseduo** [comment]
同样被投诉，上海寻死科技的律师函都在路上了

**Comment by 838239178** [comment]
逆天

**Comment by wuyilingwei** [comment]
死鸭子嘴硬

**Comment by elllusion** [comment]
> 代码都被人爆出来了， 还有脸说这话

我国不是人人都是安卓程序员。。。不是，那就成了少数人的自言自语。

**Comment by alan636** [comment]
李易峰嫖娼后开直播说：那些造谣说我嫖娼的，等你把你抓进去，我已经让律师写律师函了。下一秒李就被抓了。现在的任何声明公告可信度还剩多少？
