### ISSUE TITLE
咋用

### ISSUE THREAD

**Issue by kde-yyds** [davinci1010/pinduoduo_backdoor#75]
![Screenshot_20230404_224440_com termux](https://user-images.githubusercontent.com/106876912/229829925-55d3b353-e5a0-4e97-89c8-7d2255259132.jpg)

**Comment by kde-yyds** [comment]
没人?

**Comment by Ko-Hi-Dev** [comment]
您最有可能需要加载so文件

**Comment by kde-yyds** [comment]
哪个

**Comment by isayWu** [comment]
知道怎么用了不？  添加微信一起交流：adreamising
